import { type StudyPageContent, placeholderConcepts } from "./_shared";

export const deepLearningContent: Record<string, StudyPageContent> = {
  concepts: placeholderConcepts("Deep Learning", [
    "Forward pass and computation graphs",
    "Activation functions: ReLU, GeLU, SwiGLU, Sigmoid, Tanh — when each",
    "Loss functions for classification, regression, ranking",
    "Mini-batch SGD and what batch size affects",
    "BatchNorm, LayerNorm, RMSNorm — what they normalize and why",
    "Dropout — train-time noise injection",
    "Skip connections / residuals — why they enable deep networks",
    "Vanishing and exploding gradients",
  ]),
  "backprop-optimizers": placeholderConcepts("Backprop & Optimizers", [
    "Backprop = chain rule + dynamic programming over a computation graph",
    "Vanilla SGD, momentum, Nesterov",
    "Adam: adaptive per-parameter learning rates",
    "AdamW: decoupled weight decay (modern standard)",
    "Learning rate schedules: warmup, cosine, linear",
    "Gradient clipping for stability",
    "Mixed precision training (FP16 / BF16) for speed",
  ]),
  cnns: placeholderConcepts("CNNs", [
    "Convolution: weight sharing + locality",
    "Stride, padding, dilation",
    "Pooling: max, average, global",
    "Receptive field math",
    "Classic architectures: LeNet, AlexNet, VGG, ResNet, EfficientNet",
    "Transfer learning: feature extraction vs fine-tuning",
    "Modern alternatives: Vision Transformers (ViT)",
  ]),
  "rnns-lstm": placeholderConcepts("RNNs & LSTM", [
    "Hidden state and the recurrence relation",
    "Why vanilla RNNs fail on long sequences",
    "LSTM gates: input, forget, output",
    "GRU as a simpler alternative",
    "Bidirectional RNNs",
    "Why transformers replaced RNNs in NLP",
    "Where RNNs still win: small models, streaming, low-latency",
  ]),
  transformers: placeholderConcepts("Transformers & Attention", [
    "Self-attention: Q, K, V projections, scaled dot-product",
    "Multi-head attention",
    "Positional encoding: absolute, learned, RoPE, ALiBi",
    "Encoder, decoder, encoder-decoder variants",
    "Causal masking for autoregressive generation",
    "FlashAttention and other efficient implementations",
    "Why O(n²) attention scales — and what long-context tricks exist",
  ]),
  regularization: placeholderConcepts("Regularization in DL", [
    "Weight decay (L2 in disguise)",
    "Dropout — placement matters",
    "Data augmentation as implicit regularization",
    "Early stopping — when it&apos;s the strongest tool",
    "Label smoothing",
    "Batch / Layer norm as regularizers",
    "Mixup, CutMix, CutOut",
  ]),
};
